#ifndef KEYWORD_H
#define KEYWORD_H

enum c_keyword
{
	C_KEYWORD_AUTO, C_KEYWORD_BREAK, C_KEYWORD_CASE, C_KEYWORD_CHAR,
	C_KEYWORD_CONST, C_KEYWORD_CONTINUE, C_KEYWORD_DEFAULT, C_KEYWORD_DO,
	C_KEYWORD_DOUBLE, C_KEYWORD_ELSE, C_KEYWORD_ENUM, C_KEYWORD_EXTERN,
	C_KEYWORD_FLOAT, C_KEYWORD_FOR, C_KEYWORD_GOTO, C_KEYWORD_IF,
	C_KEYWORD_INLINE, C_KEYWORD_INT, C_KEYWORD_LONG, C_KEYWORD_REGISTER,
	C_KEYWORD_RESTRICT, C_KEYWORD_RETURN, C_KEYWORD_SHORT,
	C_KEYWORD_SIGNED, C_KEYWORD_SIZEOF, C_KEYWORD_STATIC, C_KEYWORD_STRUCT,
	C_KEYWORD_SWITCH, C_KEYWORD_TYPEDEF, C_KEYWORD_UNION,
	C_KEYWORD_UNSIGNED, C_KEYWORD_VOID, C_KEYWORD_VOLATILE,
	C_KEYWORD_WHILE, C_KEYWORD_ALIGNAS, C_KEYWORD_ALIGNOF,
	C_KEYWORD_ATOMIC, C_KEYWORD_BOOL, C_KEYWORD_COMPLEX, C_KEYWORD_GENERIC,
	C_KEYWORD_IMAGINARY, C_KEYWORD_NORETURN, C_KEYWORD_STATIC_ASSERT,
	C_KEYWORD_THREAD_LOCAL,
};

#endif
